import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';

function escHtml(s) { return (s || '').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }

export function generateHTML(review, meta) {
  const sc = review.score >= 95 ? '#22c55e' : review.score >= 80 ? '#eab308' : '#ef4444';
  const rows = (review.issues || []).map((i) => {
    const c = i.severity === 'red' ? '#ef4444' : i.severity === 'yellow' ? '#eab308' : '#22c55e';
    const icon = i.severity === 'red' ? '🔴' : i.severity === 'yellow' ? '🟡' : '🟢';
    return `<tr>
      <td style="color:${c};font-weight:600;white-space:nowrap">${icon} ${i.severity.toUpperCase()}</td>
      <td><code>${escHtml(i.file) || '-'}</code>${i.line ? `:${i.line}` : ''}</td>
      <td><strong>${escHtml(i.title)}</strong><br><span style="color:#94a3b8">${escHtml(i.desc)}</span></td>
      <td><code style="font-size:12px">${escHtml(i.fix)}</code></td>
    </tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Review Report — ${meta.date}</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f172a;color:#e2e8f0;padding:24px;max-width:960px;margin:0 auto}
h1{font-size:20px;color:#22d3ee;margin-bottom:4px}
.meta{color:#64748b;font-size:13px;margin-bottom:24px}
.sc{display:flex;align-items:center;gap:24px;background:#1e293b;border-radius:16px;padding:24px;margin-bottom:24px;border:1px solid #334155}
.ring{width:80px;height:80px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:700;border:4px solid ${sc};color:${sc};flex-shrink:0}
.detail{flex:1}.detail .sum{font-size:15px;margin-bottom:8px}
.badges{display:flex;gap:8px;flex-wrap:wrap}
.b{padding:4px 10px;border-radius:6px;font-size:12px;font-weight:600}
.br{background:#ef444420;color:#ef4444;border:1px solid #ef444440}
.by{background:#eab30820;color:#eab308;border:1px solid #eab30840}
.bg{background:#22c55e20;color:#22c55e;border:1px solid #22c55e40}
.bp{background:#22c55e20;color:#22c55e;border:1px solid #22c55e40;font-size:14px;padding:6px 14px}
.bf{background:#ef444420;color:#ef4444;border:1px solid #ef444440;font-size:14px;padding:6px 14px}
table{width:100%;border-collapse:collapse;margin-top:16px;font-size:13px}
th{text-align:left;padding:8px 12px;background:#1e293b;color:#94a3b8;border-bottom:1px solid #334155;font-weight:600;font-size:12px;text-transform:uppercase}
td{padding:10px 12px;border-bottom:1px solid #1e293b;vertical-align:top}
tr:hover{background:#1e293b40}
code{background:#0f172a;padding:2px 6px;border-radius:4px;font-size:12px;word-break:break-all}
.sec{margin-top:24px}.sec h2{font-size:15px;color:#94a3b8;margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid #1e293b}
.ft{margin-top:32px;padding-top:16px;border-top:1px solid #1e293b;color:#475569;font-size:12px;text-align:center}
</style>
</head>
<body>
<h1>🤖 AI Code Review Report</h1>
<div class="meta">${meta.date} · ${meta.model} · ${meta.mode || ''} · ${meta.extra || ''}</div>
<div class="sc">
  <div class="ring">${review.score}</div>
  <div class="detail">
    <div class="sum">${escHtml(review.summary) || '—'}</div>
    <div class="badges">
      <span class="${review.score >= (meta.threshold || 95) ? 'b bp' : 'b bf'}">${review.score >= (meta.threshold || 95) ? '✅ PASS' : '❌ BLOCKED'}</span>
      ${review.red ? `<span class="b br">🔴 ${review.red} Critical</span>` : ''}
      ${review.yellow ? `<span class="b by">🟡 ${review.yellow} Warning</span>` : ''}
      ${review.green ? `<span class="b bg">🟢 ${review.green} Info</span>` : ''}
    </div>
  </div>
</div>
<div class="sec">
  <h2>Issues (${(review.issues || []).length})</h2>
  ${(review.issues || []).length === 0
    ? '<div style="text-align:center;padding:32px;color:#22c55e;font-size:16px">✅ No issues found</div>'
    : `<table><thead><tr><th>Level</th><th>File</th><th>Issue</th><th>Fix</th></tr></thead><tbody>${rows}</tbody></table>`}
</div>
<div class="ft">Generated by ai-review-pipeline · Model: ${meta.model} · ⚠️ AI Review does not replace human Code Review</div>
</body></html>`;
}

export function writeReport({ review, meta, outputDir, open }) {
  const outDir = resolve(process.cwd(), outputDir);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const prefix = meta.mode === 'fix' ? 'pipeline' : 'review';
  const reportPath = resolve(outDir, `${prefix}-${ts}.html`);
  writeFileSync(reportPath, generateHTML(review, meta), 'utf-8');

  if (open) {
    try {
      const cmd = process.platform === 'win32' ? 'start' : process.platform === 'darwin' ? 'open' : 'xdg-open';
      execSync(`${cmd} "${reportPath}"`, { stdio: 'ignore' });
    } catch { /* can't auto-open */ }
  }
  return reportPath;
}
